name: ktlintCheck1

on:
  pull_request:
    branches:
      - master

jobs:
  check:
    runs-on: windows-latest
    steps:
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: 'check version java'
        run: java --version
      - name: 'ktlint'
        run: ./gradlew ktlintCheck --daemon
